services:
  tests:
    build:
      context: ./tests
    container_name: hw7-tests
    depends_on:
      producer:
        condition: service_healthy
      aggregation:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      PRODUCER_URL: "http://producer:8000"
      AGGREGATION_URL: "http://aggregation:8010"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "8123"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "analytics"
      POSTGRES_USER: "analytics"
      POSTGRES_PASSWORD: "analytics"
